### ISSUE TITLE
数据库的结构

### ISSUE THREAD

**Issue by LIlGG** [mohuishou/scuplus-go#58]
rt，想学习一下这个小程序。但是后台这里由于对Go语言了解的不是很多，从代码中反向研究数据库结构实在是一件很费力的事情。所以可否发一份只包含数据结构的数据库文件？万分感谢。
我的邮箱：1103069291@qq.com

**Comment by mohuishou** [comment]
数据结构都在model里面，如果只是想看看小程序，可以直接使用前端资源文件，然后看一下接口文档一般就可以了

**Comment by LIlGG** [comment]
> 数据结构都在model里面，如果只是想看看小程序，可以直接使用前端资源文件，然后看一下接口文档一般就可以了

谢谢。感谢回答。主要是想借鉴您的这个，然后用其他语言在本地搭建一个。Model里面的数据也看到了，不过还是感觉有点云里雾里，所以才发issues想要个数据结构文件。。
